app.name=HackathonPlatform

db.driver=org.postgresql.Driver
db.url=${DB_URL:jdbc:postgresql://localhost:5432/hackathon_db?sslmode=disable}
db.username=${DB_USERNAME:hackathon_user}
db.password=${DB_PASSWORD:hackathon_pwd}

hibernate.show_sql=${HIBERNATE_SHOW_SQL:false}
hibernate.hbm2ddl.auto=update

cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000}